### ISSUE TITLE
UseAsyncSuffix should not fire for overriding methods

### ISSUE THREAD

**Issue by paulomorgado** [DotNetAnalyzers/AsyncUsageAnalyzers#33] opened 2015-09-07 11:43 UTC
If the class being derived from is ill designed and doesn't suffix asynchronous methods with Async, there's nothing the derived class can do about it, so this should not be a warning.

**Comment by sharwell** [comment] 2015-09-07 15:33
Agreed, we use the same convention in StyleCopAnalyzers.

**Comment by sharwell** [comment] 2015-09-10 17:51
Duplicate of #30

**Closed by sharwell** 2015-09-10 17:51 UTC
Labels: duplicate
